var express = require("express");
var router = express.Router();

let cities = [
{name:	"Alaminos", province: "Pangasinan"},
{name:	"Angeles City", province: "Pampanga"},
{name:	"Antipolo", province: "Rizal"},
{name:	"Bacolod", province: "Negros Occidental"	},
{name:	"Bacoor", province:	"Cavite"},
{name:	"Bago",province: "Negros Occidental"},
{name:	"Baguio", province:	"Benguet"},
{name:	"Bais", province:	"Negros Oriental"},
{name:	"Balanga", province: "Bataan"},
{name:	"Batac", province:	"Ilocos Norte"},
{name:	"Batangas City", province:  "Batangas"},
{name:	"Bayawan", province: "Negros Oriental"},
{name:	"Baybay", province:	"Leyte"},
{name:	"Bayugan", province:  "Agusan del Sur"},
{name:	"Biñan", province:	"Laguna"},
{name:	"Bislig", province:	"Surigao del Sur"},
{name:	"Bogo", province:"Cebu"},
{name:	"Borongan",province:	"Eastern Samar"},
{name:	"Butuan", province:	"Agusan del Norte"},
{name:	"Cabadbaran", province:	"Agusan del Norte"},
{name:	"Cabanatuan", province:	"Nueva Ecija"},
{name:	"Cabuyao", province:	"Laguna"},
{name:	"Cadiz", province:"Negros Occidental"},
{name:	"Cagayan de Oro", province:	"Misamis Oriental"},
{name:	"Calaca",province:	"Batangas"},
{name:	"Calamba",province:	"Laguna"},
{name:	"Calapan",province:	"Oriental Mindoro"},
{name:	"Calbayog",province:	"Samar"},
{name:	"Candon",province:	"Ilocos Sur"},
{name:	"Canlaon",province:	"Negros Oriental"},
{name:	"Carcar",province:	"Cebu"},
{name:	"Catbalogan",province:	"Samar"},
{name:	"Cauayan",province:	"Isabela"},
{name:	"Cavite City",province:	"Cavite"},
{name:	"Cebu City",province:	"Cebu"	},
{name:	"Cotabato City",province:	"Maguindanao del Norte"},
{name:	"Dagupan",province:	"Pangasinan"},
{name:	"Danao"	,province:	"Cebu"},
{name:	"Dapitan",province:	"Zamboanga del Norte"},
{name:	"Dasmariñas",province:	"Cavite"},
{name:	"Davao City",province:	"Davao del Sur"},
{name:	"Digos"	,province:	"Davao del Sur"	},
{name:	"Dipolog",province:	"Zamboanga del Norte"},
{name:	"Dumaguete",province:	"Negros Oriental"	},
{name:	"El Salvador",province:	"Misamis Oriental"},
{name:	"Escalante",province:	"Negros Occidental"},
{name:	"Gapan"	,province:	"Nueva Ecija"},
{name:	"General Santos",province:	"South Cotabato"},
{name:	"General Trias",province:	"Cavite"},
{name:	"Gingoog" ,province:	"Misamis Oriental"	},
{name:	"Guihulngan",province:	"Negros Oriental"	},
{name:	"Himamaylan",province:	"Negros Occidental"},
{name:	"Ilagan"	,province:	"Isabela"},
{name:	"Tacurong"	,province:	"Sultan Kudarat"},
{name:	"Tagaytay"	,province:	"Cavite"},
{name:	"Tagbilaran",province:	"Bohol"},
{name:	"Tagum"	,province:	"Davao del Norte"},
{name:	"Talisay"	,province:	"Cebu"},
{name:	"Talisay"	,province:	"Negros Occidental"},
{name:	"Tanauan"	,province:	"Batangas"},
{name:	"Tandag"	,province:	"Surigao del Sur"},
{name:	"Tangub"	,province:	"Misamis Occidental"},
{name:	"Tanjay"	,province:	"Negros Oriental"},
{name:	"Tarlac City"	,province:	"Tarlac"},
{name:	"Tayabas"	,province:	"Quezon"},
{name:	"Toledo"	,province:	"Cebu"},
{name:	"Trece Martires",province:	"Cavite"},
{name:	"Tuguegarao",province:	"Cagayan"},
{name:	"Urdaneta"	,province:	"Pangasinan"},
{name:	"Valencia"	,province:	"Bukidnon"},
{name:	"Victorias"	,province:	"Negros Occidental"},
{name:	"Vigan" , province:	"Ilocos Sur"},
{name:	"Zamboanga City",province:	"Zamboanga del Sur"}
  
];

router.get("/", (req, res, next) => {
    res.send(cities);
});

module.exports = router;